pepper_dcm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Controllers ------------------------------------------------
  LeftArm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RightArm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - HeadYaw
      - HeadPitch
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Pelvis_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - HipRoll
      - HipPitch
      - KneePitch
    pid: {p: 100.0, i: 0.01, d: 10.0}
  LeftHand_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LHand
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RightHand_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RHand
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Effort Controllers ---------------------------------------
  WheelFL_controller:
    type: effort_controllers/JointEffortController
    joint: WheelFL
  WheelFR_controller:
    type: effort_controllers/JointEffortController
    joint: WheelFR
  WheelB_controller:
    type: effort_controllers/JointEffortController
    joint: WheelB
